### ISSUE TITLE
Feature: User can view characters and differentiate between owned and unowned

### ISSUE THREAD

**Issue by arazon005** [arazon005/front-end-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to look through a database of characters and mark specific ones as owned or unowned.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will press a button to change a container's styling to indicate whether or not the character is owned.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/user-attachments/assets/350f6813-3276-4df7-99a2-7c5346ebc404)
![image](https://github.com/user-attachments/assets/6131c8cd-568d-4dc5-918e-cfbd57d71919)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create a grid of containers populated with hard-coded character info.
 - [ ] Once styling is complete, populate the grid with containers with character info with data pulled from the API.
 - [ ] Set default modifiable character info (levels, ownership, etc.).
- [ ] While hovering over a container, blur the character image and display their name and add a button to mark them as owned.
- [ ] When clicking a container, open a modal (modal data will be handled in feature two).
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Store the character data to local storage.

- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
